name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Deno environment
      uses: denolib/setup-deno@v2.3.0
      with:
        deno-version: v1.x
    - name: Run lint
      run: deno lint --unstable
    - name: Run tests
      run: deno test